CREATE DATABASE IF NOT EXISTS hue CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'secret';
GRANT ALL PRIVILEGES ON hue.* TO 'root'@'%';
FLUSH PRIVILEGES;
