docker.sources = netcat-source
docker.sinks = logger-sink
docker.channels = memory-channel

docker.sources.netcat-source.type = netcat
docker.sources.netcat-source.bind = 0.0.0.0
docker.sources.netcat-source.port = 44444
docker.sources.netcat-source.channels = memory-channel

docker.sinks.logger-sink.type = logger
docker.sinks.logger-sink.channel = memory-channel

docker.channels.memory-channel.type = memory
docker.channels.memory-channel.capacity = 1000
docker.channels.memory-channel.transactionCapacity = 100